version: "3"
services:
  micro-frontends-forums-app:
    image: micro-frontends-forums-app:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
